package config

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

// Config is runtime configuration loaded from file + environment.
type Config struct {
	DiscordToken         string
	DiscordApplicationID string
	AllowedGuildIDs      map[string]struct{}
	RequireMention       bool
	DefaultCWD           string
	QueueSize            int
	Workers              int
	JobTimeout           time.Duration
	PiBinary             string
	// Extra args after --mode rpc (from PI_ARGS).
	PiArgs []string

	// SessionDir is where pi writes session JSONL files.
	SessionDir string
	// SessionIndexPath maps Discord threads -> session files.
	SessionIndexPath string
	// PersistSessions resumes pi sessions across restarts (default true).
	PersistSessions bool

	// ConfigPath is where file-backed settings were loaded from (if any).
	ConfigPath string
}

// Load reads configuration from an optional config file, then environment
// variables (env wins). Returns ErrMissingToken if no Discord token is set.
func Load() (Config, error) {
	// Load dotenv-style file first so explicit env can override.
	path := resolveConfigPath()
	if path != "" {
		_ = loadEnvFile(path) // best-effort; missing file is fine
	}

	cfg := Config{
		DiscordToken:         strings.TrimSpace(os.Getenv("DISCORD_TOKEN")),
		DiscordApplicationID: strings.TrimSpace(os.Getenv("DISCORD_APPLICATION_ID")),
		RequireMention:       envBool("REQUIRE_MENTION", true),
		DefaultCWD:           envOr("PI_CWD", mustGetwd()),
		QueueSize:            envInt("QUEUE_SIZE", 64),
		Workers:              envInt("WORKERS", 1),
		JobTimeout:           envDuration("JOB_TIMEOUT", 10*time.Minute),
		PiBinary:             envOr("PI_BINARY", "pi"),
		SessionDir:           envOr("PI_SESSION_DIR", defaultSessionDir()),
		SessionIndexPath:     envOr("PI_SESSION_INDEX", defaultSessionIndexPath()),
		PersistSessions:      envBool("PI_PERSIST_SESSIONS", true),
		ConfigPath:           path,
	}

	if raw := strings.TrimSpace(os.Getenv("ALLOWED_GUILD_IDS")); raw != "" {
		cfg.AllowedGuildIDs = make(map[string]struct{})
		for _, id := range strings.Split(raw, ",") {
			id = strings.TrimSpace(id)
			if id != "" {
				cfg.AllowedGuildIDs[id] = struct{}{}
			}
		}
	}

	if raw := strings.TrimSpace(os.Getenv("PI_ARGS")); raw != "" {
		cfg.PiArgs = strings.Fields(raw)
		for _, a := range cfg.PiArgs {
			if a == "--no-session" {
				cfg.PersistSessions = false
				break
			}
		}
	}

	if cfg.Workers < 1 {
		cfg.Workers = 1
	}
	if cfg.DiscordToken == "" {
		return cfg, ErrMissingToken
	}
	return cfg, nil
}

// ErrMissingToken means the user still needs setup.
var ErrMissingToken = fmt.Errorf("DISCORD_TOKEN is not set")

// DefaultConfigPath returns the preferred on-disk config location.
func DefaultConfigPath() string {
	if dir, err := os.UserConfigDir(); err == nil && dir != "" {
		return filepath.Join(dir, "pi-bridge", "config.env")
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "pi-bridge.env"
	}
	return filepath.Join(home, ".pi-bridge.env")
}

// Save writes essential Discord settings to path as dotenv.
func Save(path string, cfg Config) error {
	if path == "" {
		path = DefaultConfigPath()
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		// If path has no dir (e.g. "pi-bridge.env"), ignore.
		if filepath.Dir(path) != "." {
			return fmt.Errorf("create config dir: %w", err)
		}
	}

	var b strings.Builder
	b.WriteString("# pi-bridge config — keep this private\n")
	b.WriteString("# Generated by: pi-bridge setup\n\n")
	fmt.Fprintf(&b, "DISCORD_TOKEN=%s\n", cfg.DiscordToken)
	if cfg.DiscordApplicationID != "" {
		fmt.Fprintf(&b, "DISCORD_APPLICATION_ID=%s\n", cfg.DiscordApplicationID)
	}
	if len(cfg.AllowedGuildIDs) > 0 {
		ids := make([]string, 0, len(cfg.AllowedGuildIDs))
		for id := range cfg.AllowedGuildIDs {
			ids = append(ids, id)
		}
		fmt.Fprintf(&b, "ALLOWED_GUILD_IDS=%s\n", strings.Join(ids, ","))
	}
	fmt.Fprintf(&b, "REQUIRE_MENTION=%t\n", cfg.RequireMention)
	if cfg.DefaultCWD != "" {
		fmt.Fprintf(&b, "PI_CWD=%s\n", cfg.DefaultCWD)
	}
	fmt.Fprintf(&b, "PI_PERSIST_SESSIONS=%t\n", cfg.PersistSessions)
	if cfg.SessionDir != "" {
		fmt.Fprintf(&b, "PI_SESSION_DIR=%s\n", cfg.SessionDir)
	}

	if err := os.WriteFile(path, []byte(b.String()), 0o600); err != nil {
		return fmt.Errorf("write config: %w", err)
	}
	return nil
}

func resolveConfigPath() string {
	if p := strings.TrimSpace(os.Getenv("PI_BRIDGE_CONFIG")); p != "" {
		return p
	}
	// Prefer local project file if present, else user config dir.
	local := "pi-bridge.env"
	if st, err := os.Stat(local); err == nil && !st.IsDir() {
		return local
	}
	def := DefaultConfigPath()
	if st, err := os.Stat(def); err == nil && !st.IsDir() {
		return def
	}
	// Still return default so Save knows where to write later.
	return def
}

func loadEnvFile(path string) error {
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()

	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, val, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		key = strings.TrimSpace(key)
		val = strings.TrimSpace(val)
		val = strings.Trim(val, `"'`)
		// Don't override variables already set in the environment.
		if _, exists := os.LookupEnv(key); exists {
			continue
		}
		_ = os.Setenv(key, val)
	}
	return sc.Err()
}

func envOr(key, fallback string) string {
	if v := strings.TrimSpace(os.Getenv(key)); v != "" {
		return v
	}
	return fallback
}

func envBool(key string, fallback bool) bool {
	v := strings.TrimSpace(os.Getenv(key))
	if v == "" {
		return fallback
	}
	b, err := strconv.ParseBool(v)
	if err != nil {
		return fallback
	}
	return b
}

func envInt(key string, fallback int) int {
	v := strings.TrimSpace(os.Getenv(key))
	if v == "" {
		return fallback
	}
	n, err := strconv.Atoi(v)
	if err != nil {
		return fallback
	}
	return n
}

func envDuration(key string, fallback time.Duration) time.Duration {
	v := strings.TrimSpace(os.Getenv(key))
	if v == "" {
		return fallback
	}
	d, err := time.ParseDuration(v)
	if err != nil {
		return fallback
	}
	return d
}

func mustGetwd() string {
	wd, err := os.Getwd()
	if err != nil {
		return "."
	}
	return wd
}

func defaultSessionDir() string {
	if dir, err := os.UserConfigDir(); err == nil && dir != "" {
		return filepath.Join(dir, "pi-bridge", "sessions")
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "pi-bridge-sessions"
	}
	return filepath.Join(home, ".pi-bridge", "sessions")
}

func defaultSessionIndexPath() string {
	if dir, err := os.UserConfigDir(); err == nil && dir != "" {
		return filepath.Join(dir, "pi-bridge", "session-index.json")
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "session-index.json"
	}
	return filepath.Join(home, ".pi-bridge", "session-index.json")
}
